export type AppUserProfile = {
  id: string;
  authUserId: string;
  username: string;
  avatarUrl: string;
  bannerUrl: string;
  title: string;
  faction: string;
  bio: string;
  wallet: string;
  xp: number;
  level: number;
  streak: number;
  trustScore: number;
  sybilScore: number;
  contributionTier: string;
  reputationRank: number;
  questsCompleted: number;
  raidsCompleted: number;
  rewardsClaimed: number;
  status: "active" | "flagged";
};
